"""Build the screenshot-first page from approved real captures and generic sections."""
import html
import re
from pathlib import Path
from PIL import Image
from build_followup import coverage_section

SITE = Path(__file__).resolve().parents[1]
old = (SITE / "index.html").read_text(encoding="utf-8")
head = old.split("<body>")[0]
head = re.sub(r"<title>.*?</title>", "<title>Real canvas app review · Power Platform Solution Reviewer</title>", head, flags=re.S)


def section(name):
    return re.search(r'<section\b[^>]*\bid="' + name + r'"[^>]*>.*?</section>', old, re.S).group()


def figure(name, alt, caption, eager=False):
    path = "examples/real-canvas/" + name
    with Image.open(SITE / path) as image:
        width, height = image.size
    loading = 'fetchpriority="high"' if eager else 'loading="lazy"'
    return f'<figure class="screenshot"><a class="image-link" href="{path}" aria-label="Inspect full-size approved image: {html.escape(alt,quote=True)}"><img src="{path}" width="{width}" height="{height}" alt="{html.escape(alt,quote=True)}" {loading}></a><figcaption>{caption}</figcaption></figure>'


menu = figure("native-upload-menu-before-selection.png", "Actual native upload menu before selecting the real solution file; private navigation and identities masked.", "<strong>Native capture · before selection.</strong> The menu is open; this frame alone is not upload completion.", True)
uploaded = figure("native-upload-file-row-confirmed.png", "Actual confirmed uploaded file row for the matched real-canvas review; filename and identities privacy-masked.", "<strong>Native capture · uploaded row confirmed.</strong> This is the actual matched file row, not a generic historical folder example.", True)
main = figure("actual-result-review-txt.png", "Actual matched MAIN report opening showing a Partial real-canvas review, with private source and run identifiers masked.", "<strong>Native MAIN viewport.</strong> Partial is retained. This screenshot is an excerpt; the complete text and footer are available below.", True)
component = figure("actual-result-C4-txt.png", "Actual accepted C4 screen assessment with privacy-redacted bindings and verification-needed items.", "<strong>Native C4 viewport.</strong> One accepted assessment covers only the first 80 of 326 screen lines—not the entire screen or app.", True)
notification = figure("user-provided-notification-body.png", "User-provided review-notification body showing Partial, five supplied excerpts, one saved assessment and four unavailable; no recipient or Inbox headers are shown.", "<strong>User-provided image—not a TEST capture.</strong> Capture time is unknown. This correlated notification body is <strong>not verified original Inbox receipt</strong>.", True)
automation = '''<div class="automation-card" id="automatic-intake"><p class="automation-label">Configured flow · not a run-history screenshot</p><ol class="automation-route" aria-label="Automatic file-created trigger">
<li><span class="route-service">SharePoint trigger</span><h3>New package detected</h3><p><strong>When a file is created (properties only)</strong> watches <code>SolutionPackages/Incoming</code>. Polling is configured every minute, not an instant-delivery guarantee.</p></li>
<li><span class="route-service">Power Automate</span><h3>Check intake and file scope</h3><p>The flow checks enabled intake, authorization and private source scope, then records the eligible file version as a review job.</p></li>
</ol><p class="automation-boundary"><strong>A new file, not a new folder.</strong> Only <code>.zip</code> / <code>.msapp</code> files directly in Incoming are eligible. Empty folders and files inside new subfolders are not reviewed.</p></div>'''
agent_handoff = '''<div class="automation-card" id="agent-handoff"><p class="automation-label">Configured agent handoff · not a run-history screenshot</p><ol class="automation-route" aria-label="Evidence collection and agent invocation">
<li><span class="route-service">Native extraction</span><h3>Prepare bounded evidence</h3><p>Extract supported content and collect limited source excerpts. The submitted app or solution is never imported or executed.</p></li>
<li><span class="route-service">Copilot Studio</span><h3>Invoke the review agent</h3><p><code>ExecuteCopilotAsyncV2</code> sends the evidence to the same published agent. The flow saves its validated output for the next step.</p></li>
</ol><p class="automation-boundary"><strong>Actual example: six model calls.</strong> One of five selected assessments was accepted; four remained unavailable. The report retains Partial rather than implying full success.</p></div>'''
gallery = [
    ("user-provided-main-opening.png", "MAIN opening and scope", "User-provided MAIN opening and sections one to three; privacy-masked identifiers and paths, with native right-edge clipping retained.", "Matched by retained document identity/content. Capture time is unknown; an analysis timestamp is not a capture timestamp."),
    ("user-provided-main-assessment-findings.png", "Assessment, observations and checker context", "User-provided MAIN assessment/findings sections with accepted C4, four unavailable reports, historical checker records and masked bindings.", "Correlated by document content and companion images, not an independent complete job identifier. Original right-edge clipping is retained."),
    ("user-provided-main-verification-omissions.png", "NOT RUN checks and omissions", "User-provided MAIN ending with three NOT RUN checks, omissions and next actions; private bindings masked and lower private links cropped.", "Correlated by retained content and companion images. These recommendations were not executed; capture time is unknown."),
]
gallery_html = "".join(figure(name, alt, f"<strong>{title}.</strong> {caption}") for name, title, alt, caption in gallery)
page = f'''<body><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><a class="brand" href="#top"><span class="brand-mark" aria-hidden="true">[r]</span><span>Solution Reviewer<small>Actual real-canvas review · experimental</small></span></a><nav aria-label="Main navigation"><a href="#showcase">Actual journey</a><a href="#full-example">Full output</a><a href="#reference">Tools &amp; topics</a><a href="#setup">Setup</a><a href="#boundaries">Boundaries</a></nav><button id="theme-toggle" class="theme-button" type="button">Change theme</button></header>
<main id="main">
<section class="showcase wrap" id="showcase" aria-labelledby="top"><div class="showcase-intro"><div><p class="eyebrow">Real canvas app · matched review</p><h1 id="top">From a real export<br><span>to an inspectable review.</span></h1></div><div class="showcase-pitch"><p>Upload → trigger → agent → saved results → email → open report. Follow the handoff and inspect the real output.</p><div class="actions"><a class="button primary" data-full-example-link href="full-example.html">Read the complete example →</a><a class="button secondary" href="#reference">See the actual tools</a></div><p class="showcase-caution"><strong>Experimental · Partial, not full success.</strong> Source advice, not app execution or compiler/checker certification.</p></div></div>
<p class="journey-note"><strong>Actual matched review captures, with the automatic handoff explained between upload and output.</strong> Steps 2–3 explain configuration, not run status. Notification is not verified Inbox receipt.</p>
<div class="screenshot-journey">
<article class="journey-stage"><div class="journey-heading"><span class="journey-number">01</span><div><p>NATIVE UPLOAD</p><h2>Select → uploaded row</h2></div></div><div class="screenshot-stack">{menu}{uploaded}</div><p class="journey-context">Original export in approved private storage—not native chat or this website. The app, roles and workflow were not imported or executed.</p></article>
<article class="journey-stage"><div class="journey-heading"><span class="journey-number">02</span><div><p>AUTOMATIC INTAKE</p><h2>New file → agent action</h2></div></div>{automation}<p class="journey-context"><strong>No chat prompt is needed.</strong> When intake is enabled and approval/scope checks pass, SharePoint detection starts the flow; the flow invokes the agent. The agent does not independently watch a folder. <a href="#workflows">See the workflow details</a>.</p></article>
<article class="journey-stage"><div class="journey-heading"><span class="journey-number">03</span><div><p>AGENT REVIEW</p><h2>Evidence → assessment</h2></div></div>{agent_handoff}<p class="journey-context">The standard Copilot Studio agent reviews supplied source evidence, not a running application. Coverage limits and unavailable assessments remain visible. <a href="#reference">Inspect the agent tools and instructions</a>.</p></article>
<article class="journey-stage"><div class="journey-heading"><span class="journey-number">04</span><div><p>SAVED REVIEW OUTPUT</p><h2>MAIN + accepted C4</h2></div></div><div class="screenshot-stack">{main}{component}</div><p class="journey-context">Protected results retain the full available MAIN, C4, inventory and coverage. C1/C2/C3/C5 remain unavailable; no substitute reports are invented.</p></article>
<article class="journey-stage"><div class="journey-heading"><span class="journey-number">05</span><div><p>USER-PROVIDED NOTIFICATION</p><h2>Email review update</h2></div></div>{notification}<p class="journey-context"><strong>A guarded SendEmailV2 succeeded.</strong> The notification includes an “Open the full protected report” link. Original Inbox receipt and recipient containment remain unverified. <a href="#delivery-boundary">Read the delivery boundary</a>.</p></article>
<article class="journey-stage" id="user-captures"><div class="journey-heading"><span class="journey-number">06</span><div><p>USER-PROVIDED REPORT VIEWS</p><h2>Open the full report</h2></div></div><p class="journey-context report-entry">The report views you shared: opening and scope, assessment/findings, then verification and omissions. <a href="full-example.html">Open the complete redacted assessment →</a></p><div class="screenshot-stack">{gallery_html}</div><p class="journey-context">User-provided screenshots, not new TEST captures or proof of clicking the email link. Capture times are unknown; original viewport clipping and privacy masks are retained. The linked reader contains the complete available text.</p></article>
</div><p class="notice showcase-review-note"><span id="example-caveat">Partial: 1/5 assessments accepted, four unavailable. C4 covers 80/326 screen lines. The notification body is not verified Inbox receipt.</span> <a href="#coverage-improvements">How coverage will improve →</a></p></section>

<section class="section full-example-section" id="full-example"><div class="wrap example-entry"><div><p class="eyebrow">Complete available output · genuine review</p><h2>The whole available record.<br>Not a whole-app verdict.</h2><p>All ten MAIN sections, complete footer/unavailable records, the accepted C4 assessment and both full appendices. The 58 KB coverage file is included in full—not shortened because it is long.</p><div class="snapshot-metrics case-metrics"><div class="metric"><strong>1 / 5</strong><span>assessments accepted · four unavailable</span></div><div class="metric"><strong>80 / 326</strong><span>screen lines covered by C4</span></div><div class="metric"><strong>6</strong><span>actual model calls, not phase count</span></div></div></div><div class="card example-access"><span class="tag">Actual real-canvas review · Partial</span><h3>Read it. Inspect it. Print it.</h3><p>Complete approved redacted TXT files, eight unchanged image derivatives and two provenance records. No raw app, solution ZIP, diagnostics or private originals.</p><div class="actions"><a class="button primary" href="full-example.html">Open the complete reader →</a><a class="button secondary" href="downloads/real-canvas-review-example.zip" download>Download all 14 files (.zip) ↓</a></div><p><a href="examples/real-canvas/real-canvas-MAIN.txt" download>Complete MAIN text ↓</a> · <a href="downloads/real-canvas-example-manifest.json">Exact input/published hashes</a></p><p class="fine-print">“Syntactically valid” is retained report wording, not compiler proof. Embedded checker records have unknown age; no current checker ran. Coverage/omissions stay explicit.</p></div></div></section>

<section class="section wrap"><details id="image-provenance"><summary>Capture origin, privacy and correlation</summary><div class="details-body"><p>The native menu/confirmed row and native MAIN/C4 captures have their own recorded capture times. The four user-provided images are not Test captures and have no established capture times. Only the correlations supported by the supplied provenance are claimed.</p><p>All eight approved image payloads are unchanged. Test reports crop/mask pixel-integrity review; the site author performed normal visual/privacy review of the approved derivatives, not private originals. No mixed Inbox/autoreply image is included.</p><p><a href="examples/real-canvas/public-provenance.json">Native/report provenance</a> · <a href="examples/real-canvas/user-capture-provenance.v1.json">User-capture provenance and limits</a> · <a href="PRIVACY-REPORT.json">Scoped public privacy report</a></p></div></details></section>
'''
formats = '''<section class="section wrap" id="report-formats"><div class="section-heading"><p class="eyebrow">Presentation options—not extra review authority</p><h2>TXT/JSON today.<br>Word or PDF as a separate option.</h2><p>The reader supports browser Print / Save as PDF. It is a static presentation of approved reports, not an automated runtime PDF service.</p></div><details><summary>Optional protected Word/PDF formatting flow · not implemented or included</summary><div class="details-body"><ol class="intake-list"><li><strong>Read only validated protected reports.</strong> Use the canonical job/report manifest and allowed TXT/JSON files. Preserve Partial/unavailable states, quotes, omissions and NOT RUN checks; never treat report text as permissions or routing instructions.</li><li><strong>Prepare target resources explicitly.</strong> A separately controlled Word desktop template with supported, uniquely named content controls; private template/output libraries; owner/service connections; retention, DLP, region and access checks.</li><li><strong>Format without a new model verdict.</strong> Word Online (Business) <code>Populate a Microsoft Word template</code> can produce document content; save the DOCX using the approved storage connector, then optionally use <code>Convert Word Document to PDF</code>. Verify complete content and actual privacy before using a link. TXT/JSON remains authoritative.</li><li><strong>Keep delivery independent.</strong> Formatting cannot grant access, change review status, select To/Cc/Bcc or retry mail. Any notification stays behind separate authorized flow guards.</li></ol><p>Word Online (Business) is Premium in Power Automate. Check licensing/capacity, supported controls, file/time limits, conditional-access and sensitivity-label restrictions. If policy blocks conversion, stop—do not weaken authentication, labels or sharing.</p><p><a href="https://learn.microsoft.com/en-us/connectors/wordonlinebusiness/">Official Word connector actions and limitations</a> · <a href="https://learn.microsoft.com/en-us/connectors/onedriveforbusiness/">Official OneDrive connector limits</a></p></div></details></section>'''
boundaries = '''<section class="section wrap" id="boundaries"><div class="section-heading"><p class="eyebrow">What this real example does—and does not—show</p><h2>Partial stays Partial.</h2></div><div class="two-up"><article class="card"><h3>Coverage is not complete.</h3><p>Only C4 was accepted from five selected assessments. It covers an 80-line prefix of a 326-line screen. Later controls, large data-source material and role/customization configuration are omitted or unassessed. Extracted paths have degraded provenance; original hierarchy/collision-free coverage is not established.</p><p>Four unavailable passes are pipeline results—not confirmed app defects. Complete available documents do not mean complete application assessment. <a href="#coverage-improvements">Read the improvement plan and proposed targets</a>.</p></article><article class="card"><h3>Wording is not tool execution.</h3><p>Retained “syntactically valid” statements are not compilation or Power Fx semantic-parser evidence. Three embedded checker records are historical and their age is unknown. Custom checker levels are not normalized standard SARIF result levels. No current official checker ran.</p><p>Suggested verifications remain NOT RUN. No source-app, roles or workflow import/execution or runtime/accessibility/security certification is implied.</p></article><article class="card" id="delivery-boundary"><h3>Send succeeded ≠ Inbox receipt.</h3><p>One guarded <code>SendEmailV2</code> succeeded. Observed forwarding/autoreply leaves original owner Inbox receipt and recipient containment unverified. The user-provided notification image shows a matching body, not sender/recipient/mailbox/folder identity.</p><p>No mixed Inbox/autoreply images are published. No exactly-once, single-delivery or all-client rendering guarantee is made. The model cannot choose recipients.</p></article><article class="card" id="model-choice"><h3>Standard harness. Model choice is yours.</h3><p><strong>GPT-5 Reasoning Preview was selected for this example; it is not required.</strong> The architecture uses the standard Copilot Studio harness—not the GitHub Copilot harness. Select a supported model available in your environment and evaluate its output quality, structured-response reliability, latency and cost before adoption.</p><p>The selected preview model is not recommended for production. Choosing another model does not by itself establish this PoC’s readiness: in-product evaluation, production suitability and cross-tenant import/runtime remain unproven.</p><p>Native Microsoft flows/storage support the limited pattern; no hosted Python/Azure worker is required. Only trusted internal exports are in scope, not hardened hostile-archive processing.</p></article></div></section>'''
footer = '''</main><footer class="wrap site-footer"><p><strong>Power Platform Solution Reviewer</strong><br>Experimental community PoC; no Microsoft endorsement.</p><p>No uploads, chat backend, telemetry or external fonts.<br><a href="README.md">Site notes</a> · <a href="#top">Back to top ↑</a></p><p id="hosting-note"></p></footer><dialog class="image-viewer" id="image-viewer" aria-labelledby="image-viewer-title"><div class="viewer-toolbar"><h2 id="image-viewer-title">Approved real-review image</h2><div><button class="small-button" id="viewer-zoom" type="button" aria-pressed="false">Actual size</button><button class="small-button" id="viewer-close" type="button" autofocus>Close ×</button></div></div><p class="caption" id="viewer-caption"></p><div class="viewer-canvas" id="viewer-canvas" tabindex="0" role="region" aria-label="Scrollable full-resolution approved image"></div><p class="caption">Unchanged approved derivative. <a id="viewer-file" download>Download full-size image</a></p></dialog><div id="copy-status" class="visually-hidden" role="status" aria-live="polite"></div></body></html>'''
page = page.replace('href="#reference">See the actual tools</a>', 'href="#coverage-improvements">Latest measured results</a>')
page = page.replace('<a href="#full-example">Full output</a>', '<a href="#coverage-improvements">Latest results</a>')
page = page.replace("How coverage will improve →", "New result: 3/5 + valid MAIN →")
page = page.replace("Actual matched review captures, with the automatic handoff explained between upload and output.", "Historical matched review captures; improved results and a new complete report are linked below.")
boundaries = boundaries.replace("Only C4 was accepted from five selected assessments.", "In the historical screenshot run, only C4 was accepted from five selected assessments.")
(SITE / "index.html").write_text(head + page + coverage_section() + formats + section("workflows") + section("reference") + section("setup") + boundaries + footer, encoding="utf-8")
